server:
  port: 8082
  ssl:
    key-store: classpath:server.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myserver
br:
  db:
    database: br-trade
    host: 192.168.147.3
    pw: 123456
feign:
  okhttp:
    enabled: true