server:
  port: 8082
  ssl:
    key-store: classpath:server.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myserver
br:
  db:
    database: br-trade
    host: 192.168.147.3
    pw: 123456
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
rocketmq:
  name-server: 192.168.147.3:9876 # 替换为你的NameServer地址
  producer:
    group: order-producer-group
  consumer:
    group: order-consumer-group